name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - staging

jobs:
  prettier_eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Install modules
        run: cd fwb && npm install
        
      - name: Prettify Code
        run: cd fwb && npm run format

      - name: Lint Code
        run: cd fwb && npm run lint


